"""
Execution lifecycle: the states a run moves through and the events it emits.

Every state and every event belongs to one run_id — there is no global
"is something running" flag here.
"""
from enum import Enum


class ExecutionState(str, Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    VALIDATING = "VALIDATING"
    ALLOCATING_RESOURCES = "ALLOCATING_RESOURCES"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    PROCESSING_RESULTS = "PROCESSING_RESULTS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


TERMINAL_STATES = {ExecutionState.COMPLETED, ExecutionState.FAILED, ExecutionState.CANCELLED}
ACTIVE_STATES = {s for s in ExecutionState if s not in TERMINAL_STATES}


class EventType(str, Enum):
    EXECUTION_CREATED = "EXECUTION_CREATED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    VALIDATION_STARTED = "VALIDATION_STARTED"
    VALIDATION_COMPLETED = "VALIDATION_COMPLETED"
    RESOURCE_ALLOCATED = "RESOURCE_ALLOCATED"
    MODULE_STARTED = "MODULE_STARTED"
    MODULE_COMPLETED = "MODULE_COMPLETED"
    MODULE_FAILED = "MODULE_FAILED"
    TEST_STARTED = "TEST_STARTED"
    TEST_PASSED = "TEST_PASSED"
    TEST_FAILED = "TEST_FAILED"
    LOG = "LOG"
    SCREENSHOT = "SCREENSHOT"
    DEVICE_STATUS = "DEVICE_STATUS"
    APPIUM_STATUS = "APPIUM_STATUS"
    BROWSER_STATUS = "BROWSER_STATUS"
    ROLE_STATUS = "ROLE_STATUS"
    ALLURE_READY = "ALLURE_READY"
    RESULT_PROCESSING = "RESULT_PROCESSING"
    STATE_CHANGED = "STATE_CHANGED"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_CANCELLED = "EXECUTION_CANCELLED"


# Module status vocabulary shared with the UI (Live Execution).
MODULE_PENDING = "pending"
MODULE_RUNNING = "running"
MODULE_COMPLETED = "completed"
MODULE_FAILED = "failed"
MODULE_SKIPPED = "skipped"
